
name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

# Environment variables available to all jobs and steps in this workflow
env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: super-simple-service

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      # Configure gcloud CLI
      - name: gcloud Set up
        run: |
          gcloud config set project $PROJECT_ID

      # Build docker image
      - name: Build docker image
        run: |
          docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .
          gcloud auth configure-docker -q
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
  deploy:
    name: Deploy the app
    runs-on: self-hosted
    needs: build_docker
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy the app
        uses: appleboy/ssh-action@master
#        env:
#          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
#          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
#          IMAGE_TAG: ${{ github.sha }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: docker stop $(docker ps -f name=test_backend* -q);
          docker run -d -p 3001:3001 --env-file ./deploy_env --name test_backend_$GITHUB_SHA gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
